#!/usr/bin/env bash
set -euo pipefail

# Raspberry Pi initial setup:
# 1) Fix "Setting locale failed" warnings
# 2) Disable Wi-Fi power saving (NetworkManager + dispatcher)
# 3) Disable Broadcom brcmfmac power saving (driver-level)
#
# Run:
#   curl -fsSL https://raw.githubusercontent.com/dunnomyname/dotfiles/refs/heads/master/raspberry-init.sh | sudo bash
# or:
#   sudo bash raspberry-init.sh

need_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    echo "ERROR: Run as root (use sudo)." >&2
    exit 1
  fi
}

backup_if_exists() {
  local f="$1"
  if [[ -f "$f" ]]; then
    local ts
    ts="$(date +%Y%m%d-%H%M%S)"
    cp -a "$f" "${f}.bak.${ts}"
  fi
}

ensure_pkg() {
  local pkg="$1"
  if ! dpkg -s "$pkg" >/dev/null 2>&1; then
    apt-get update -y
    apt-get install -y "$pkg"
  fi
}

fix_locale() {
  echo "==> Fixing locale warnings..."

  # Ensure locales tooling exists
  ensure_pkg "locales"

  # Generate en_US.UTF-8 locale if not already enabled
  if [[ -f /etc/locale.gen ]]; then
    if ! grep -Eq '^[[:space:]]*en_US\.UTF-8[[:space:]]+UTF-8' /etc/locale.gen; then
      # Uncomment if present as commented, else append
      if grep -Eq '^[[:space:]]*#[[:space:]]*en_US\.UTF-8[[:space:]]+UTF-8' /etc/locale.gen; then
        sed -i 's/^[[:space:]]*#[[:space:]]*en_US\.UTF-8[[:space:]]\+UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
      else
        echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
      fi
    fi
    locale-gen >/dev/null
  fi

  # Set defaults (matches the "add LC_* lines" fix)
  # This mirrors the approach of updating /etc/default/locale to include LC_* variables. :contentReference[oaicite:0]{index=0}
  backup_if_exists /etc/default/locale
  cat >/etc/default/locale <<'EOF'
# File generated by setup script (safe to edit)
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_ALL=en_US.UTF-8
EOF

  # Also apply via update-locale (Debian-standard)
  update-locale LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_ALL=en_US.UTF-8 >/dev/null || true

  echo "   Locale set to en_US.UTF-8 (will fully apply after reboot/login)."
}

ensure_networkmanager() {
  if ! command -v nmcli >/dev/null 2>&1; then
    echo "ERROR: NetworkManager not found. This script is written for the NetworkManager setup." >&2
    echo "       Install it or adapt for dhcpcd." >&2
    exit 1
  fi
}

disable_nm_wifi_powersave() {
  echo "==> Disabling Wi-Fi power saving (NetworkManager)..."

  # 1) NetworkManager global config to prevent powersave
  mkdir -p /etc/NetworkManager/conf.d
  backup_if_exists /etc/NetworkManager/conf.d/wifi-powersave.conf
  cat >/etc/NetworkManager/conf.d/wifi-powersave.conf <<'EOF'
[connection]
wifi.powersave = 2
EOF

  # 2) Dispatcher script to force it off on link-up
  mkdir -p /etc/NetworkManager/dispatcher.d
  backup_if_exists /etc/NetworkManager/dispatcher.d/99-wifi-powersave
  cat >/etc/NetworkManager/dispatcher.d/99-wifi-powersave <<'EOF'
#!/bin/sh
IFACE="$1"
STATUS="$2"

# Force-disable Wi-Fi power save on wlan0 when link comes up
if [ "$IFACE" = "wlan0" ] && [ "$STATUS" = "up" ]; then
  /sbin/iw dev wlan0 set power_save off 2>/dev/null || true
fi
EOF
  chmod +x /etc/NetworkManager/dispatcher.d/99-wifi-powersave

  systemctl restart NetworkManager

  # Try immediately (best effort)
  if command -v iw >/dev/null 2>&1; then
    iw dev wlan0 set power_save off 2>/dev/null || true
  fi

  echo "   NetworkManager configured."
}

disable_brcmfmac_powersave() {
  echo "==> Disabling Broadcom brcmfmac power saving (driver-level)..."

  mkdir -p /etc/modprobe.d
  backup_if_exists /etc/modprobe.d/brcmfmac.conf
  cat >/etc/modprobe.d/brcmfmac.conf <<'EOF'
options brcmfmac power_save=0
EOF

  echo "   brcmfmac configured (takes effect after reboot)."
}

show_status() {
  echo "==> Status checks (best effort)..."
  echo "--- /etc/default/locale ---"
  cat /etc/default/locale || true
  echo

  if command -v iw >/dev/null 2>&1; then
    echo "--- iw power_save ---"
    iw dev wlan0 get power_save 2>/dev/null || echo "wlan0 not available right now"
    echo
  fi

  echo "--- NetworkManager powersave config ---"
  if [[ -f /etc/NetworkManager/conf.d/wifi-powersave.conf ]]; then
    cat /etc/NetworkManager/conf.d/wifi-powersave.conf
  else
    echo "missing"
  fi
  echo

  echo "--- brcmfmac config ---"
  if [[ -f /etc/modprobe.d/brcmfmac.conf ]]; then
    cat /etc/modprobe.d/brcmfmac.conf
  else
    echo "missing"
  fi
  echo
}

main() {
  need_root
  ensure_networkmanager

  fix_locale
  disable_nm_wifi_powersave
  disable_brcmfmac_powersave
  show_status

  echo "DONE. Reboot recommended:"
  echo "  sudo reboot"
}

main "$@"

